jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '19'
    - continue-on-error: true
      name: Setup Gradle Dependencies Cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-v2-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts',
          'gradle.properties') }}
        path: ~/.gradle/caches
    - continue-on-error: true
      name: Setup Gradle Wrapper Cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-v2-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties')
          }}
        path: ~/.gradle/wrapper
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: export PHPSTORM_ENV=skip && ./gradlew check verifyPlugin buildPlugin
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
